const sampleData=[
    { "text": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde" },
    { "text": "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", "author": "Albert Einstein" },
    { "text": "So many books, so little time.", "author": "Frank Zappa" },
    { "text": "A room without books is like a body without a soul.", "author": "Marcus Tullius Cicero" },
    { "text": "You only live once, but if you do it right, once is enough.", "author": "Mae West" },
    { "text": "Be the change that you wish to see in the world.", "author": "Mahatma Gandhi" },
    { "text": "In three words I can sum up everything I've learned about life: it goes on.", "author": "Robert Frost" },
    { "text": "If you tell the truth, you don't have to remember anything.", "author": "Mark Twain" },
    { "text": "A friend is someone who knows all about you and still loves you.", "author": "Elbert Hubbard" },
    { "text": "To live is the rarest thing in the world. Most people exist, that is all.", "author": "Oscar Wilde" },
    { "text": "Without music, life would be a mistake.", "author": "Friedrich Nietzsche" },
    { "text": "We accept the love we think we deserve.", "author": "Stephen Chbosky" },
    { "text": "It is never too late to be what you might have been.", "author": "George Eliot" },
    { "text": "It does not do to dwell on dreams and forget to live.", "author": "J.K. Rowling" },
    { "text": "Good friends, good books, and a sleepy conscience: this is the ideal life.", "author": "Mark Twain" },
    { "text": "Life is what happens to us while we are making other plans.", "author": "Allen Saunders" },
    { "text": "I have not failed. I've just found 10,000 ways that won't work.", "author": "Thomas A. Edison" },
    { "text": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston S. Churchill" },
    { "text": "If you can't explain it to a six-year-old, you don't understand it yourself.", "author": "Albert Einstein" },
    { "text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt" },
    { "text": "Imagination is more important than knowledge.", "author": "Albert Einstein" },
    { "text": "Everything you can imagine is real.", "author": "Pablo Picasso" },
    { "text": "If you're going through hell, keep going.", "author": "Winston Churchill" },
    { "text": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson" },
    { "text": "It is our choices that show what we truly are, far more than our abilities.", "author": "J.K. Rowling" },
    { "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs" },
    { "text": "If you want to live a happy life, tie it to a goal, not to people or things.", "author": "Albert Einstein" },
    { "text": "Everything has beauty, but not everyone sees it.", "author": "Confucius" },
    { "text": "It is not how much we have, but how much we enjoy, that makes happiness.", "author": "Charles Spurgeon" },
    { "text": "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", "author": "Buddha" },
    { "text": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu" },
    { "text": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama" },
    { "text": "In the end, we will remember not the words of our enemies, but the silence of our friends.", "author": "Martin Luther King Jr." },
    { "text": "That which does not kill us makes us stronger.", "author": "Friedrich Nietzsche" },
    { "text": "It is never too late to be what you might have been.", "author": "George Eliot" },
    { "text": "The only impossible journey is the one you never begin.", "author": "Tony Robbins" },
    { "text": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt" },
    { "text": "Turn your wounds into wisdom.", "author": "Oprah Winfrey" },
    { "text": "Challenges are what make life interesting and overcoming them is what makes life meaningful.", "author": "Joshua J. Marine" },
    { "text": "Change your thoughts and you change your world.", "author": "Norman Vincent Peale" },
    { "text": "It is not the years in your life but the life in your years that counts.", "author": "Abraham Lincoln" },
    { "text": "Success is how high you bounce when you hit bottom.", "author": "George S. Patton" },
    { "text": "Our lives begin to end the day we become silent about things that matter.", "author": "Martin Luther King Jr." },
    { "text": "It always seems impossible until it's done.", "author": "Nelson Mandela" },
    { "text": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau" },
    { "text": "If you want to fly, you have to give up the things that weigh you down.", "author": "Toni Morrison" },
    { "text": "You can't go back and change the beginning, but you can start where you are and change the ending.", "author": "C.S. Lewis" },
  ];
  module.exports={ data: sampleData};
  